-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'INSERVE_CUSTOMERS_IMPORTED';

-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'INSERVE_CUSTOMER_IMPORT_FAILED';

-- AlterEnum
ALTER TYPE "SyncJobId" ADD VALUE 'INSERVE_CUSTOMER_IMPORT';
