-- Extend SIM varchar fields for Simhuis ICCIDs (up to 34 chars was too long for 20)
ALTER TABLE "sims" ALTER COLUMN "iccid" TYPE VARCHAR(40);
ALTER TABLE "sims" ALTER COLUMN "msisdn" TYPE VARCHAR(30);
ALTER TABLE "sims" ALTER COLUMN "imsi" TYPE VARCHAR(20);
ALTER TABLE "sims" ALTER COLUMN "provider" TYPE VARCHAR(150);
ALTER TABLE "sims" ALTER COLUMN "simType" TYPE VARCHAR(100);
ALTER TABLE "sims" ALTER COLUMN "apn" TYPE VARCHAR(200);

-- Add new AuditAction enum values (Simhuis batch sync actions)
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BATCH_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BATCH_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BATCH_ERROR';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SIMHUIS_SYNCED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SIMHUIS_SYNC_FAILED';
